/*
 * Generated by Spring Initializr. This file is a downloader stub used by
 * the mvnw script when the wrapper jar is not yet present.
 * Do NOT move it into src/main/java — the Maven Wrapper expects it here.
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.file.Files;
import java.util.Properties;

public final class MavenWrapperDownloader {
    private static final String DEFAULT_DOWNLOAD_URL =
        "https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.5.6/maven-wrapper-0.5.6.jar";
    private static final String PROPERTIES_PATH = ".mvn/wrapper/maven-wrapper.properties";
    private static final String WRAPPER_JAR_PATH = ".mvn/wrapper/maven-wrapper.jar";

    public static void main(String[] args) throws IOException {
        File baseDirectory = new File(args.length > 0 ? args[0] : ".");
        File propertiesFile = new File(baseDirectory, PROPERTIES_PATH);
        String url = DEFAULT_DOWNLOAD_URL;
        if (propertiesFile.exists()) {
            try (FileInputStream fis = new FileInputStream(propertiesFile)) {
                Properties props = new Properties();
                props.load(fis);
                url = props.getProperty("wrapperUrl", url);
            }
        }
        File jar = new File(baseDirectory, WRAPPER_JAR_PATH);
        if (!jar.getParentFile().exists()) {
            jar.getParentFile().mkdirs();
        }
        URL website = new URL(url);
        try (ReadableByteChannel rbc = Channels.newChannel(website.openStream())) {
            Files.copy(java.nio.channels.Channels.newInputStream(rbc), jar.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
    }
}
